### ISSUE TITLE
mosca_precompute.py crash when the epipolar mask is all false

### ISSUE THREAD

**Issue by zhou13** [JiahuiLei/MoSca#10]
I get the following error when running the reproduce.sh on Sintel/Sleeping2:
```
  File "/mnt/task_runtime/src/mosca/prior/moca_processor.py", line 258, in process_tap
    return spatracker_process_folder(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/task_runtime/.venv/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/task_runtime/src/mosca/prior/tracking/spatracker_wrapper.py", line 204, in spatracker_process_folder
    queries = get_uniform_random_queries(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/task_runtime/src/mosca/prior/tracking/tracking_utils.py", line 150, in get_uniform_random_queries
    q = tracker_get_query_uv(mask, fid=t, num=int(target_num) * 3)
                                              ^^^^^^^^^^^^^^^
ValueError: cannot convert float NaN to integer
```

It is because when computing the dynamic tap, the mask is all false as the scene is almost static. This makes target_num to be NaN. It seems that it does not affect the reconstruction, but crashing is bad.

**Comment by zhou13** [comment]
In addition, I have some trouble to reproduce the Sintel number on table 7. I saw run-to-run variation on scores. Both are slightly worse than the reported number. I am not sure if this is normal as I am using a slightly different environment (e.g., I am on CUDA 12.4).
Run1: 
```
alley_2: 
      ate:  0.015
rpe_trans:  0.003
  rpe_rot:  0.157
ambush_4
ambush_4: 
      ate:  0.042
rpe_trans:  0.027
  rpe_rot:  0.259
ambush_5
ambush_5: 
      ate:  0.014
rpe_trans:  0.010
  rpe_rot:  0.209
ambush_6
ambush_6: 
      ate:  0.050
rpe_trans:  0.024
  rpe_rot:  0.432
cave_2
cave_2: 
      ate:  0.561
rpe_trans:  0.214
  rpe_rot:  1.359
cave_4
cave_4: 
      ate:  0.016
rpe_trans:  0.007
  rpe_rot:  0.098
market_2
market_2: 
      ate:  0.002
rpe_trans:  0.001
  rpe_rot:  0.065
market_5
market_5: 
      ate:  0.130
rpe_trans:  0.068
  rpe_rot:  0.448
market_6
market_6: 
      ate:  0.019
rpe_trans:  0.005
  rpe_rot:  0.110
shaman_3
shaman_3: 
      ate:  0.002
rpe_trans:  0.000
  rpe_rot:  0.052
sleeping_1
sleeping_1: 
      ate:  0.008
rpe_trans:  0.001
  rpe_rot:  0.070
sleeping_2
sleeping_2: 
      ate:  0.003
rpe_trans:  0.003
  rpe_rot:  0.054
temple_2
temple_2: 
      ate:  0.085
rpe_trans:  0.008
  rpe_rot:  0.127
temple_3
temple_3: 
      ate:  0.462
rpe_trans:  0.150
  rpe_rot:  0.944

100%|██████████| 14/14 [00:00<00:00, 15526.24it/s]
ave_ate:      0.101
ave_rpe_t:    0.037
ave_rpe_rot:  0.313
```

Run2:
```
Reconstructing on Sintel dataset (default setting)
alley_2
alley_2: 
      ate:  0.015
rpe_trans:  0.003
  rpe_rot:  0.154
ambush_4
ambush_4: 
      ate:  0.042
rpe_trans:  0.027
  rpe_rot:  0.259
ambush_5
ambush_5: 
      ate:  0.014
rpe_trans:  0.011
  rpe_rot:  0.207
ambush_6
ambush_6: 
      ate:  0.086
rpe_trans:  0.033
  rpe_rot:  0.646
cave_2
cave_2: 
      ate:  0.520
rpe_trans:  0.193
  rpe_rot:  1.231
cave_4
cave_4: 
      ate:  0.016
rpe_trans:  0.007
  rpe_rot:  0.098
market_2
market_2: 
      ate:  0.003
rpe_trans:  0.001
  rpe_rot:  0.065
market_5
market_5: 
      ate:  0.395
rpe_trans:  0.144
  rpe_rot:  0.549
market_6
market_6: 
      ate:  0.019
rpe_trans:  0.005
  rpe_rot:  0.110
shaman_3
shaman_3: 
      ate:  0.002
rpe_trans:  0.000
  rpe_rot:  0.052
sleeping_1
sleeping_1: 
      ate:  0.008
rpe_trans:  0.001
  rpe_rot:  0.071
sleeping_2
sleeping_2: 
      ate:  0.003
rpe_trans:  0.003
  rpe_rot:  0.054
temple_2
temple_2: 
      ate:  0.085
rpe_trans:  0.008
  rpe_rot:  0.127
temple_3
temple_3: 
      ate:  0.471
rpe_trans:  0.150
  rpe_rot:  0.975
ave_ate:      0.120
ave_rpe_t:    0.042
ave_rpe_rot:  0.328
```
